import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-col">
        <div className="flex-grow pb-16">{children}</div>
      </body>
    </html>
  );
}
